### ISSUE TITLE
Add tutorial to download data before running

### ISSUE THREAD

**Issue by tobegit3hub** [domluna/memn2n#12]
I follow the instruction to run `single.py` but it fails. It would be better to add tutorial about how and where to download the data.

```
$ python ./single.py
Started Task: 1
Traceback (most recent call last):
  File "./single.py", line 32, in <module>
    train, test = load_task(FLAGS.data_dir, FLAGS.task_id)
  File "/home/tobe/code/memn2n/data_utils.py", line 14, in load_task
    files = os.listdir(data_dir)
OSError: [Errno 2] No such file or directory: 'data/tasks_1-20_v1-2/en/'
```

**Comment by tobegit3hub** [comment]
Maybe add this in `README.md` and I would like to create the PR for this 😃 
```
mkdir ./data/
cd ./data/
wget http://www.thespermwhale.com/jaseweston/babi/tasks_1-20_v1-2.tar.gz
tar xzvf ./data/tasks_1-20_v1-2.tar.gz
```
